services:
  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    ports:
      - "9000:3000"
  
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports :
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
