services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
    ports: !override #override pour éviter les conflits avec les ports déja défini dans le compose principal
      - 4200:4200
    volumes:
      - ./Front:/app
      - /app/node_modules

  backend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./Back:/app
      - /app/node_modules