services:
  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    image: flor3473/brainbox:backend
    ports:
      - "9000:3000"
    volumes:
      - ./Back:/app
      - /app/node_modules
    env_file:
      - ./Back/.env
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    image: flor3473/brainbox:frontend
    ports:
      - 4200:4200
    volumes:
      - ./Front:/app
      - /app/node_modules
   
    depends_on:
      - backend

volumes:
  ollama:
  Front:
  Back:
